# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Lisa Charpentier Designer Fabricante

# Short description (goes below the title; it will also be used in the RSS feed)
description: Designer industriel et artiste de formation, je suis une fabricante de tous les jours basée à Montréal.

# Your name, as you want it to appear underneath each post and in the footer
author: Lisa Charpentier

# Your email if you want it to be linked on the contact page
author_email: info@lisacharpentier.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

imagesurl: /img/
scriptsurl: /scripts/

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://lisacharpentier.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: /:categories/:title/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

repository: siteliz/siteliz.github.io

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "post"

collections:
  meubles:
    output: true
    display_name: Les meubles
    weight: a
  services:
    output: true
    display_name: Les services
    weight: z
  etc:
    output: true
    display_name: Le reste
    weight: m
  chiffres-lettres:
    output: true
    display_name: Les chiffres et les lettres
    weight: e